-- MySQL Script generated by MySQL Workbench
-- 05/12/16 01:08:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoTcc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjetoTcc` ;

-- -----------------------------------------------------
-- Schema ProjetoTcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoTcc` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoTcc` ;

-- -----------------------------------------------------
-- Table `ProjetoTcc`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTcc`.`User` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(70) NOT NULL,
  `password` VARCHAR(45) NULL,
  `fbid` VARCHAR(45) NULL,
  `avatar` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoTcc`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTcc`.`Post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idUser` BIGINT NOT NULL,
  `url` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_User_idx` (`idUser` ASC),
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `ProjetoTcc`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
