-- MySQL Script generated by MySQL Workbench
-- 05/18/16 10:50:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoTcc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjetoTcc` ;

-- -----------------------------------------------------
-- Schema ProjetoTcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoTcc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `ProjetoTcc` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `fbid` TEXT NULL COMMENT '',
  `placeId` TEXT NULL COMMENT '',
  `username` VARCHAR(70) NOT NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `avatar` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUser` BIGINT NOT NULL COMMENT '',
  `url` TEXT NULL COMMENT '',
  `titulo` VARCHAR(70) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Post_User_idx` ON `Post` (`idUser` ASC)  COMMENT '';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
